spring:
  data:
    mongodb:
      uri: mongodb+srv://admin-saatvik:saatvik@cluster0.1s8fn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0/fitness-activity
      database: fitness-activity
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

server:
  port: 8082

eureka:
    client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
          register-with-eureka: true
          fetch-registry: true

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
